Update to Python 3.12.12 (#1)
* - Meter Fix:
`TypeError: DefaultSession.__init__() takes from 1 to 2 positional arguments but 3 were given` in flows_session, positional parameters now are omitted

* - Meter Fix: Packets not being processed,  overridden Method in scapy.DefaultSession  was renamed from
def on_packet_received(self, packet)  => def process(self, pkt):

* - Meter Fix:
'WARNING: Socket <scapy.utils.PcapReader object at 0x7f199c688ad0> failed with 'module 'meter.features.context.packet_direction' has no attribute 'FORWARD''. It was closed.', import was incorrect since PacketDirection was moved to 'PacketDirection'

* - Meter Fix (Statistical Features Mode) :
`WARNING: Socket <scapy.utils.PcapReader object at 0x7fd8ba0da450> failed with ''EDecimal' object cannot be interpreted as an integer'. It was closed.`

* - Meter Fix (Statistical Features  Mode):
`WARNING: Socket <scapy.utils.PcapReader object at 0x7fbba7bf1410> failed with 'conversion from numpy.int64 to Decimal is not supported'. It was closed.`, caused by conversion from numpy.int64 to decimal

* - Meter Fix (Statistical  Features Mode):
`RuntimeWarning: Mean of empty slice return _methods._mean(a, axis=axis, dtype=dtype,`
  and
  `RuntimeWarning: invalid value encountered in scalar divide ret = ret.dtype.type(ret / rcount)`; Problem is division by 0 fixed, by pre check if there are packets and if not return 0

* - Meter Fix (Interface Sniffing):
`WARNING: Socket <scapy.arch.linux.L2ListenSocket object at 0x7f50a5bfee70> failed with 'Layer ['IP'] not found'. It was closed.`, fixed by skipping all none IPv4 packet

* - Meter Fix (Interface Sniffing):
Previous flows are not stored when the capture is aborted with CTRL-C.
Problem: You can see it by yourself when starting an interface sniffing and aborting it after a while => see no "Garbage Collection Began ..." and no output is generated.
I assume before `DefaultSession` would call `toPacketList` when finish sniffing. Now these method does not exists any more
Fix: Besides the AsyncSniffer also return the `FlowSession` instance  and manual call the garbage collection

* - Analyzer Fix:
Kera imports are not working since the Keras package structure changed.

* - Analyzer Fix: Fix "models" package import in analyzer package,
so it can be called from the DoHLyzer root folder with
`python -m analyzer.main --input "./analyzer/sample_data/" --output "./analyzer/sample_data/output.json`

* - Update requirements.txt to Python 3.12.12

* - Meter Clean Up: Update README.md how the meter module can be used and removed unused import